# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudctl < Formula
  desc "Secure AWS AssumeRole session manager with MFA & Touch ID"
  homepage "https://github.com/chukul/cloudctl"
  version "1.0.8"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/chukul/cloudctl/releases/download/v1.0.8/cloudctl_1.0.8_darwin_amd64.tar.gz"
    sha256 "f0006777699ab2bd8d27d910e378ca982c70d133860342095275c15508aa2179"

    def install
      bin.install "cloudctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/chukul/cloudctl/releases/download/v1.0.8/cloudctl_1.0.8_darwin_arm64.tar.gz"
    sha256 "3443ca268653bc6955900156a002e1ce5876ab17d75140b191c5e1f9b8abe22c"

    def install
      bin.install "cloudctl"
    end
  end
end
