# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudctl < Formula
  desc "Secure AWS AssumeRole session manager with MFA & Touch ID"
  homepage "https://github.com/chukul/cloudctl"
  version "1.2.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/chukul/cloudctl/releases/download/v1.2.1/cloudctl_1.2.1_darwin_amd64.tar.gz"
    sha256 "8e894ff0ab212372b7ccd6efcfc6a1aa38659bee566b5c070db15f29ffe8f53b"

    def install
      bin.install "cloudctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/chukul/cloudctl/releases/download/v1.2.1/cloudctl_1.2.1_darwin_arm64.tar.gz"
    sha256 "98ecf4eb7c047bf6c6dac75731c17dfcebf063ea8181469e3ae1281412b6cce1"

    def install
      bin.install "cloudctl"
    end
  end
end
